// Shared run-detail sample data, inspired by agent-hub's real Couples Habits run.

const RUN = {
  project: { name: 'couples-habits', id: 'ch-42' },
  skill: 'UX Journey Reviewer',
  skillSlug: 'journey-reviewer',
  family: 'browser',
  status: 'completed',
  date: 'Tuesday, April 14, 2026',
  time: '09:25 AM',
  duration: '4m 12s',
  suite: 'a41c7bf9…',
  runId: 'b8f2c401-4e9b-4a1d-a9d2-5f6e8c9d1234',
  artifactType: 'Journey Report',

  coverage: {
    stepsCompleted: 15,
    stepsTotal: 15,
    journeys: 10,
    passed: 12,
    warnings: 1,
    failed: 2,
    heuristic: 58,
  },

  signals: { critical: 2, warning: 5, passing: 5, info: 3 },

  verdict: {
    severity: 'NEEDS WORK',
    headline:
      'Couples Habits delivers a coherent, research-grounded product experience with 2 trust-eroding bugs at critical moments.',
    summary:
      'The core daily loop (check-in) is fast and satisfying, the marketing copy is distinctive, and the one-habit-at-a-time constraint is communicated well. Three issues undermine trust: a misleading sign-in error, silent demo-init failures, and a 404 page that fails to render. Layer B coverage: 62% of flows observed end-to-end.',
  },

  recommendations: [
    {
      priority: 'P0',
      title: 'Replace misleading sign-in error',
      action: 'Use a standard "Incorrect email or password" message.',
      rationale:
        'Current copy rewrites "Invalid credentials" as "No password set" and pushes users into an unnecessary reset flow.',
      effort: 'S',
      owner: 'Frontend',
    },
    {
      priority: 'P0',
      title: 'Fix demo init service failure',
      action: 'Recover gracefully from SUPABASE_SERVICE_ROLE_KEY absence.',
      rationale:
        'Silent failure leaves users in solo mode instead of the coupled experience.',
      effort: 'M',
      owner: 'Backend',
    },
    {
      priority: 'P1',
      title: 'Add loading.tsx for authed routes',
      action: 'Eliminate the 1–2s blank flash on protected routes.',
      rationale:
        'Next.js needs a loading boundary; the current transition looks like a broken app.',
      effort: 'S',
      owner: 'Frontend',
    },
    {
      priority: 'P1',
      title: 'Render custom 404 correctly',
      action: 'Verify not-found.tsx renders on unknown routes (currently shows browser default).',
      rationale: 'Trust signal for branded shell; affects every typo.',
      effort: 'S',
      owner: 'Frontend',
    },
    {
      priority: 'P2',
      title: 'Add forward navigation to Research',
      action: 'Link inline from the research citation onto its detail page.',
      rationale: 'Readers can\'t explore citations without hitting back.',
      effort: 'S',
      owner: 'Design',
    },
  ],

  findings: [
    {
      id: 'C1',
      severity: 'critical',
      title: 'Misleading sign-in error rewrites "Invalid credentials" to "No password set"',
      category: 'Authentication',
      heuristic: 'H2 · Match between system and real world',
      location: 'app/page.tsx:83-89',
      evidence: 'step-9-err1-misleading-error.png',
      impact:
        'Users who mistyped their password are actively misdirected to a password reset flow, destroying trust.',
      recommendation:
        'Replace the error rewrite with a standard "Incorrect email or password. Please try again."',
    },
    {
      id: 'C2',
      severity: 'critical',
      title: 'Demo init fails silently when service role key missing',
      category: 'Backend',
      heuristic: 'H9 · Help users recover',
      location: 'api/demo/route.ts:24',
      evidence: 'step-3-demo-init.png',
      impact: 'Solo-mode demo instead of intended coupled experience. No toast, no server log visibility.',
      recommendation: 'Surface the init failure with a retry and a server-side error log.',
    },
    {
      id: 'W1',
      severity: 'warning',
      title: 'No loading.tsx files anywhere in the app',
      category: 'Performance',
      heuristic: 'H1 · Visibility of system status',
      location: 'app/*',
      evidence: 'step-4-auth-flash.png',
      impact: '1–2s blank flash during navigation; feels broken.',
      recommendation: 'Add route-level loading.tsx skeletons for at least the home and journal routes.',
    },
    {
      id: 'W2',
      severity: 'warning',
      title: '404 page fails to render as custom not-found',
      category: 'Navigation',
      heuristic: 'H5 · Error prevention',
      location: 'app/not-found.tsx',
      evidence: 'step-10-err2-404.png',
      impact: 'Browser default 404 page; "This page isn\'t working" for every typo.',
      recommendation: 'Verify not-found.tsx is in the right boundary.',
    },
    {
      id: 'W3',
      severity: 'warning',
      title: 'Scroll-behavior: smooth warning in console',
      category: 'Polish',
      heuristic: 'H4 · Consistency and standards',
      location: 'globals.css',
      evidence: null,
      impact: 'Repeated console warning; cosmetic only.',
      recommendation: 'Scope smooth-scroll to html or remove.',
    },
    {
      id: 'I1',
      severity: 'investigate',
      title: 'Verify 404 page rendering in standard browser',
      category: 'Navigation',
      heuristic: null,
      location: null,
      evidence: null,
      impact: 'Puppeteer may report differently than a user browser; re-verify.',
      recommendation: 'Re-run the journey against a fresh Chrome install.',
    },
    {
      id: 'N1',
      severity: 'info',
      title: 'Add forward navigation to Research page',
      category: 'Content',
      heuristic: 'H3 · User control and freedom',
      location: 'components/ResearchCitation.tsx',
      evidence: null,
      impact: 'Readers can\'t explore citations without hitting back.',
      recommendation: 'Link inline from the citation to the detail page.',
    },
    {
      id: 'N2',
      severity: 'info',
      title: 'Consolidate duplicate auth forms on homepage',
      category: 'Architecture',
      heuristic: 'H8 · Aesthetic and minimalist design',
      location: 'app/page.tsx',
      evidence: null,
      impact: 'Two forms doing the same thing; bundle + mental-load cost.',
      recommendation: 'Extract a single <AuthForm /> and render it once.',
    },
    {
      id: 'N3',
      severity: 'low',
      title: 'Add error-path journeys for form validation',
      category: 'Testing',
      heuristic: null,
      location: null,
      evidence: null,
      impact: 'Only happy-path validation is observed today.',
      recommendation: 'Extend the suite with invalid-input steps.',
    },
  ],

  sections: [
    {
      id: 'methodology',
      title: 'Methodology',
      level: 'healthy',
      summary: '15 steps across 10 journeys, 2-layer coverage model.',
      critical: 0,
      warning: 0,
    },
    {
      id: 'primary-journeys',
      title: 'Primary Journeys',
      level: 'watch',
      summary: 'P1–P3 all complete; minor scroll warning on P2.',
      critical: 0,
      warning: 1,
    },
    {
      id: 'secondary-journeys',
      title: 'Secondary Journeys',
      level: 'healthy',
      summary: 'S1–S3 all pass; breadcrumbs reliable.',
      critical: 0,
      warning: 0,
    },
    {
      id: 'error-journeys',
      title: 'Error Journeys',
      level: 'critical',
      summary: 'E1 + E2 both surface user-facing defects.',
      critical: 2,
      warning: 1,
    },
    {
      id: 'heuristic-coverage',
      title: 'Heuristic Coverage',
      level: 'watch',
      summary: '58% Nielsen H1–H10 touched; gaps in H7 + H10.',
      critical: 0,
      warning: 2,
    },
    {
      id: 'detailed-findings',
      title: 'Detailed Findings',
      level: 'critical',
      summary: '9 findings total, 2 critical.',
      critical: 2,
      warning: 3,
    },
  ],

  screenshots: [
    { id: 'step-1', name: 'step-1-landing.png', label: 'Landing' },
    { id: 'step-3', name: 'step-3-demo-init.png', label: 'Demo init' },
    { id: 'step-5', name: 'step-5-checkin.png', label: 'Check-in' },
    { id: 'step-9', name: 'step-9-err1-misleading-error.png', label: 'Sign-in error' },
    { id: 'step-10', name: 'step-10-err2-404.png', label: '404 failure' },
    { id: 'step-14', name: 'step-14-faq.png', label: 'FAQ' },
  ],

  steps: [
    { n: 1, group: 'P1', name: 'Landing → Sign up', status: 'pass' },
    { n: 2, group: 'P1', name: 'Sign up → Check-in', status: 'pass' },
    { n: 3, group: 'P1', name: 'Demo init', status: 'fail', finding: 'C2' },
    { n: 4, group: 'P2', name: 'Toggle sign-in form', status: 'pass' },
    { n: 5, group: 'P2', name: 'Check-in submit', status: 'pass' },
    { n: 6, group: 'S1', name: 'Breadcrumb back', status: 'pass' },
    { n: 7, group: 'S1', name: 'Breadcrumb to dashboard', status: 'pass' },
    { n: 8, group: 'S3', name: 'About page', status: 'pass' },
    { n: 9, group: 'E1', name: 'Invalid credentials', status: 'fail', finding: 'C1' },
    { n: 10, group: 'E2', name: '/nonexistent 404', status: 'warn', finding: 'W2' },
    { n: 11, group: 'P2', name: 'Sign-up confirm', status: 'pass' },
    { n: 12, group: 'S3', name: 'FAQ accordion', status: 'pass' },
    { n: 13, group: 'S3', name: 'Research citation', status: 'pass' },
    { n: 14, group: 'S3', name: 'FAQ re-expand', status: 'pass' },
    { n: 15, group: 'E2', name: 'Invalid invite token', status: 'pass' },
  ],
};

window.RUN = RUN;
